Metrics/ModuleLength:
  Max: 200

Style/DoubleNegation:
  Exclude:
    - 'libraries/resource_firewall_rule.rb'

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

CyclomaticComplexity:
  Max: 25

AbcSize:
  Max: 150

ClassLength:
  Max: 200

LineLength:
  Max: 250

MethodLength:
  Max: 50

PerceivedComplexity:
  Max: 50

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

AllCops:
  Include:
    - '**/metadata.rb'
    - '**/*.rb'
  Exclude:
    - 'libraries/z_provider_mapping.rb'
    - 'test/fixtures/cookbooks/firewall-test/recipes/debian_iptables.rb'
